Fix for security issue with qa-ldap-login
zakkak/qa-ldap-login pull request #28
Opened 2020-11-04 13:07 UTC by doedje

I recently discoved a security issue with qa-ldap-plugin. It is very easy to login as any ldap-user known to q2a without knowing the user's password simply by manually creating the right cookies in the browser. Especially when an attacker is familiar with the ldap being used, like in our case, where the uid is simply firstname.lastname, it is extremely easy to gain access to an account using cookie-spoofing.

This Pull Request fixes the issue. Please merge it into your forked version of qa-ldap-login so it is no longer vulnerable.

Best regards,

Remy Blom
The Netherlands

2020-11-04 22:51 UTC, zakkak requested changes
Thanks for your contribution @doedje !
Unfortunately I can't test this so I assume you have tested this and it works.

2020-11-04 22:51 UTC, zakkak commented on ldap-login.php
> +  /*
Please remove this comment since it doesn't add any value.

2020-11-04 22:51 UTC, zakkak commented on qa-ldap-process.php
> +        // REMY BLOM: DO WHAT THE SCRIPT IS SUPPOSED TO DO, DON'T SET COOKIES?!?!?!
Please remove this comment as well since it won't make any sense after this PR is merged.

2020-11-05 08:40 UTC, doedje commented
I Removed the comments as requested.
We have my forked version in production at the moment, so I can verify it works...

Best regards!

2020-11-05 19:04 UTC, zakkak approved these changes

2020-11-05 19:04 UTC, merged